import type { Metadata } from "next";
import "@/utils/globals.css";
import styles from "@/utils/fonts/futura/futura.module.css"
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Tleuliev tests",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.futura}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
