import { Toaster } from '@/components/ui/toaster'
import { nunito_sans } from '@/utils/fonts'
import '@/utils/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Tleuliev tests',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={nunito_sans.className}>
				<main>{children}</main>
				<Toaster />
			</body>
		</html>
	)
}
